Revert "Introduce wisp-client (cashapp/misk#1826)" (cashapp/misk#1827)
This reverts commit eda47222576c3e58d57bd6d691ece4425144322f for breaking downstream
consumers due to injection failure:

```
    java.lang.NoClassDefFoundError: misk/client/EnvoyClientEndpointProvider
```